{{- $skipPostgres := .Values.skipPostgres -}}
{{ if not $skipPostgres }}
{{- /*
Service for read/write connections, that is connections to the master node.
*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.postgresSvcName }}'
  labels:
    type: postgres
    cluster-name: '{{ .Values.postgresSvcName }}'
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
protocol: TCP
{{ end }}
