{{- $skipPostgres := .Values.skipPostgres -}}
{{ if not $skipPostgres }}
{{- /*
Service for load-balanced, read-only connections to the pool of PostgreSQL instances.
*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.postgresSvcName }}-ro'
  labels:
    type: postgres
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    # helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    cluster-name: '{{ .Values.postgresSvcName }}'
spec:
  clusterIP: None
  spec:
  ports:
  - port: 5432
    name: psql
  - port: 8008
    name: patronictl
  selector:
    type: postgres
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    cluster-name: '{{ .Values.postgresSvcName }}'
{{ end }}
