# ARTWORK
# Secrets that can be set via files in `./secrets/*.secret`, via command line by `--set 'pgAdminUser=xyz,pgHost=host.com,...'` or even uncomment them in the lines below.
# pgAdminUser: ''
# pgHost: ''
# pgHostRO: ''
# pgPass: ''
# pgPassRO: ''
# pgPassTeam: ''
# pgPassRep: ''
# githubOAuth: ''
# grafanaUser: ''
# grafanaPassword: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipBootstrap (will not run initial bootstrapping - creating logs and users, but you don't need to skip it - bootstrap pod detects already created resources)
# skipCrons (will not create new cronjobs, you should set it when cron jobs are already created, if you want to recreate cron jobs, delete existing ones first and do not set this flag)
# skipGrafanas (will not create Grafana deployments)
# skipPVs (will not attempt to create persistent volume claims, this is usually needed to avoid creating existing resource)
# skipProvisions (will not create provisioning pods, usually not needed, provisioning pod will detect already provisioned projects and only provision new ones)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipServices (will not attempt to create services (Load Balancers))
# skipBootstrap: 1
# skipCrons: 1
# skipGrafanas: 1
# skipPVs: 1
# skipProvisions: 1
# skipSecrets: 1
# skipServices: 1
#
# You can overwrite the number of CPU autodetected in each pod, setting this to 1 will make each pod single-threaded
# nCPUs: 0
#
# Other evrironment options
# bootstrapCommand: 'sleep'
# bootstrapCommandArgs:
#   - "36000"
#   - "bootarg"
# cmdDebug: 1
# debug: 1
# forceComputeAll: 1
# githubDebug: 1
# grafanaCommandArgs:
#   - "36000"
#   - arg2
# nodeSelector:
#   node: devstats
# onlyMetrics: 'events,tz'
# periods: 'd7:t,m:f,q:t,y10:f'
# provisionCommand: './k8s/repos.sh'
# provisionCommand: './k8s/affs.sh'
# provisionCommand: './k8s/vars.sh'
# provisionCommand: './k8s/clear_devstats_running_flag.sh'
# provisionCommand: './k8s/set_provisioned_flag.sh'
# provisionCommand: 'sleep'
# provisionCommandArgs:
#   - "36000"
# queryOut: 1
# reposDir: "/root/devstats_repos/"
# skipMetrics: 'users_activity,committers_cum'
# https://itnext.io/efs-persistent-volumes-on-aws-kubernetes-193e0035bbfb
# storageAccessModes: ReadWriteMany
# storageClass: efs
# syncCommandArgs:
#   - "syncarg"
affiliations: 'github_users.json'
bootstrapCommand: './example/deploy_all.sh'
bootstrapLDrop: ''
bootstrapNoCreate: ''
bootstrapPodName: devstats-provision-bootstrap
bootstrapRestartPolicy: Never
bootstrapUDrop: ''
companyAcq: "companies.yaml"
concurrencyPolicy: Forbid
fullnameOverride: devstats
grafanaCommand: 'grafana_start.sh'
grafanaImage: 'lukaszgryglicki/devstats-grafana'
grafanaNReplicas: 1
grafanaPodName: devstats-grafana
grafanaPort: 3000
grafanaRestartPolicy: Always
grafanaSecret: grafana-secret
imagePullPolicy: Always
indexCronsFrom: 0
indexCronsTo: 100
indexGrafanasFrom: 0
indexGrafanasTo: 100
indexProvisionsFrom: 0
indexProvisionsTo: 100
indexPVsFrom: 0
indexPVsTo: 100
indexServicesFrom: 0
indexServicesTo: 100
limitsBootstrapCPU: '2000m'
limitsBootstrapMemory: '2Gi'
limitsCronsCPU: '6000m'
limitsCronsMemory: '16Gi'
limitsGrafanasCPU: '2000m'
limitsGrafanasMemory: '8Gi'
limitsProvisionsCPU: '8000m'
limitsProvisionsMemory: '24Gi'
name: devstats
nameOverride: devstats
oauthSecret: github-oauth
pgSecret: pg-db
proivisionImage: 'lukaszgryglicki/devstats'
projectsFile: 'example/projects.yaml'
provisionCommand: './example/deploy_all.sh'
provisionPodName: devstats-provision
provisionRestartPolicy: Never
postgresSvcName: 'devstats-postgres'
postgresImageName: 'jberkus/simple-patroni:v3'
postgresStorageSize: '100Gi'
postgresNodes: 3
pvName: devstats-pvc
requestsBootstrapCPU: '500m'
requestsBootstrapMemory: '1Gi'
requestsCronsCPU: '1000m'
requestsCronsMemory: '2Gi'
requestsGrafanasCPU: '1000m'
requestsGrafanasMemory: '1Gi'
requestsProvisionsCPU: '1000m'
requestsProvisionsMemory: '2Gi'
secretType: Opaque
servicePodName: devstats-service
serviceType: LoadBalancer
storageAccessModes: ReadWriteOnce
storageClass: gp2
syncCommand: devstats
syncImage: 'lukaszgryglicki/devstats-minimal'
syncPodName: devstats
syncRestartPolicy: Never
volumeMountName: data
volumeMountPath: '/root'
volumeName: data
useBootstrapResourcesLimits: 1
useCronsResourcesLimits: 1
useGrafanasResourcesLimits: 1
useProvisionsResourcesLimits: 1
waitForBootstrap: 30
labels:
  name: devstats
projects:
  - proj: cncf
    db: cncf
    icon: 'cncf'
    org: 'CNCF'
    repo: 'cncf/landscape'
    cron: '7 * * * *'
    disk: 30Gi
    i: 0
